name: Publish Quarto Site

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Use a stable version

      - name: Install Jupyter and Python deps
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbformat nbconvert ipykernel pandas matplotlib numpy

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render site
        run: quarto render

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAT }}  # or GH_PAT if you added it
          publish_dir: ./_site
          publish_branch: gh-pages  # ✅ Force it to create/push to gh-pages

